/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ved
 */
public class tempPage extends javax.swing.JFrame {

    /**
     * Creates new form tempPage
     */
    public tempPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arena1 = new javax.swing.JButton();
        arena2 = new javax.swing.JButton();
        arena5 = new javax.swing.JButton();
        arena6 = new javax.swing.JButton();
        arena3 = new javax.swing.JButton();
        arena4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        arena1.setFont(new java.awt.Font("Ubuntu", 0, 15)); // NOI18N
        arena1.setText("Arena1");
        arena1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arena1MouseClicked(evt);
            }
        });
        arena1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arena1ActionPerformed(evt);
            }
        });

        arena2.setText("Arena2");
        arena2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arena2MouseClicked(evt);
            }
        });

        arena5.setText("Arena5");
        arena5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arena5MouseClicked(evt);
            }
        });

        arena6.setText("Arena5");
        arena6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arena6MouseClicked(evt);
            }
        });

        arena3.setText("Arena3");
        arena3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arena3MouseClicked(evt);
            }
        });

        arena4.setText("Arena4");
        arena4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                arena4MouseClicked(evt);
            }
        });
        arena4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arena4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(arena2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(arena4, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(arena6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(arena1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(arena3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(arena5, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(arena5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(arena3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(arena1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(arena6, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                    .addComponent(arena4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(arena2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arena1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arena1ActionPerformed

    }//GEN-LAST:event_arena1ActionPerformed

    private void arena4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arena4ActionPerformed

    }//GEN-LAST:event_arena4ActionPerformed

    private void arena1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arena1MouseClicked
                page1 p1=new page1();
        p1.setVisible(true);
    }//GEN-LAST:event_arena1MouseClicked

    private void arena2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arena2MouseClicked
                page2 p2=new page2();
        p2.setVisible(true);
    }//GEN-LAST:event_arena2MouseClicked

    private void arena3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arena3MouseClicked
                page3 p3=new page3();
        p3.setVisible(true);
    }//GEN-LAST:event_arena3MouseClicked

    private void arena4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arena4MouseClicked
               page4 p4=new page4();
        p4.setVisible(true);
    }//GEN-LAST:event_arena4MouseClicked

    private void arena5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arena5MouseClicked
                page5 p5=new page5();
        p5.setVisible(true);
    }//GEN-LAST:event_arena5MouseClicked

    private void arena6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_arena6MouseClicked
               page6 p6=new page6();
        p6.setVisible(true);
    }//GEN-LAST:event_arena6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tempPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tempPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tempPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tempPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tempPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arena1;
    private javax.swing.JButton arena2;
    private javax.swing.JButton arena3;
    private javax.swing.JButton arena4;
    private javax.swing.JButton arena5;
    private javax.swing.JButton arena6;
    // End of variables declaration//GEN-END:variables
}
